# Generated by Django 3.1.6 on 2021-02-17 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='auction',
            field=models.ManyToManyField(related_name='auction_house_set', through='catalog.Auction', to=settings.AUTH_USER_MODEL),
        ),
    ]
